import { HeaderWrapper, Container } from "@/components/shared";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Pizza | Checkout",
  description: "Generated by create next app",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <HeaderWrapper hasSearch={false} hasCartButton={false} />
      </Container>

      {children}
    </main>
  );
}
