import { Header, Container } from "@/components/shared";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Next Pizza | Checkout",
  description: "Generated by create next app",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Suspense fallback={null}>
          <Header hasSearch={false} hasCartButton={false} />
        </Suspense>
      </Container>

      {children}
    </main>
  );
}
