import { HeaderWrapper } from "@/components/shared/header-wrapper";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Pizza",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen">
      <HeaderWrapper hasSearch={false} hasCartButton={false} />
      {children}
      {modal}
    </main>
  );
}
